name: cv
channels:
  - defaults
dependencies:
  - pytorch::torchvision
  - pytorch::torchaudio
  - conda-forge::cudnn=8.1
  - python=3.10.*
  - jupyter
  - numpy=1.23.*
  - pandas=1.5.*
  - opencv
  - matplotlib
  - seaborn
  - IPython
  - Pillow
  - psutil
  - tqdm
  - libpng
  - jpeg
  - pip
  - pip:
    - torch
