name: cv
channels:
  - conda-forge
dependencies:
  - python=3.10.*
  - jupyter
  - numpy=1.23.*
  - pandas=1.5.*
  - opencv
  - pytorch=1.13.0
  - cudatoolkit=11.4
  - cudnn=8.1
  - matplotlib
  - seaborn
  - IPython
  - Pillow
  - psutil
  - tqdm
  - libpng
  - jpeg
  - pip
  - pip:
    - torch
    - torchvision==0.14.0
    - torchaudio